_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.RandomRotation
    degrees: 15
  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5
  - _target_: torchvision.transforms.RandomVerticalFlip
    p: 0.5
  - _target_: torchvision.transforms.RandomGrayscale
    p: 0.2
  - _target_: torchvision.transforms.RandomPerspective
    distortion_scale: 0.5
    p: 0.5
  - _target_: torchvision.transforms.RandomAffine
    degrees: 15
    translate: [0.1, 0.1]
    scale: [0.9, 1.1]
    shear: 10
  - _target_: torchvision.transforms.RandomResizedCrop
    size: 224
    scale: [0.8, 1.0]
    ratio: [0.75, 1.33]
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.RandomErasing
    p: 0.5
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]