_target_: data.dataset_generators.ip_adapter.IpAdapterGenerator
generator: ${image_generator}
batch_size: ${batch_size}
output_dir: ${data_dir}/train/ipadapter_prompts
input_dir: ${data_dir}/val
num_images_per_label: 7