_target_: data.dataset_generators.simple_v2.SimplePromptsDatasetGenerator
generator: ${image_generator}
batch_size: ${batch_size}
output_dir: ${data_dir}/train/simple_prompts_v2
num_images_per_label: 100