defaults:
  - model: dinov2
  - dataset: llama3
  - dataset_bis: ipadapter
  - optim: adamw
  - loss_fn: cross_entropy

epochs: 10

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${dataset.train_path}
  train_dataset_bis_path: ${dataset_bis.train_path}
  real_images_val_path: ${dataset.real_images_val_path}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.test_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}

data_dir: ${root_dir}/dataset
root_dir:  ${hydra:runtime.cwd}
checkpoint_path: ${root_dir}/checkpoints/${experiment_name}.pt
checkpoint_path_bis: ${root_dir}/checkpoints/${experiment_name_bis}.pt

experiment_name: ${model.name}_${dataset.name}
experiment_name_bis: ${model.name}_${dataset_bis.name}
hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true